reportesVC/urls.py
from django.conf.urls import url

from . import views

app_name = 'reportesVC'
urlpatterns = [
    ##(?P<question_id>[0-9]+)
    ###View normal
    #url(r'^(?P<tipoNombre>[\w]+)/(?P<reporteId>[0-9]+)/$', views.reporte, name='reporte'),
    ###Quick view provided bydjango
    url(r'^$', views.index, name='index'),

    ##url(r'^rp(?P<tipoNombre>[\w]+)/$', views.reportes, name='reportes'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/$', views.reportes, name='reportes'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/new/$', views.creaReporte, name='creaReporte'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivo/$', views.subirArchivo, name='subirArchivo'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/$', views.ReporteView.as_view(), name='reporte'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarZip/$', views.descargarZip, name='descargarZip'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarRepCXC/$', views.descargarRepCXC, name='descargarRepCXC'),

    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/$', views.calculos, name='calculos'),
    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/new/$', views.ejecutaComisiones, name='ejecutaComisiones'),
    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivo/$', views.subirArchivoCal, name='subirArchivoCal'),
    url(r'^cal(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/$', views.CalculoView.as_view(), name='calculo'),
    url(r'^cal(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarFile/$', views.descargarFile, name='descargarFile'),

    url(r'^admin/Conta/$', views.adminConta, name='adminConta'),

    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionBancos$', views.conciliacionBancos, name='conciliacionBancos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaBancos/$', views.conciliaBancos, name='conciliaBancos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivoCon/$', views.subirArchivoCon, name='subirArchivoCon'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionSAT$', views.conciliacionSAT, name='conciliacionSAT'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaSAT/$', views.conciliaSAT, name='conciliaSAT'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionIngresos$', views.conciliacionIngresos, name='conciliacionIngresos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaIngresos/$', views.conciliaIngresos, name='conciliaIngresos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionMontoClave$', views.conciliacionMontoClave, name='conciliacionMontoClave'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaMontoClave/$', views.conciliaMontoClave, name='conciliaMontoClave'),
]

reportesVC/templates/reportesVC/base.html
<!DOCTYPE html>
{% load static %}
{% load menu %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}
{% bootstrap_css %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block tituloPagina %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'reportesVC/DT_bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'reportesVC/style.css' %}" />

</head>
<body>
    {% block menuu %}
        {% generate_menu %}
        {% with menu=menus.main %}
            {% include "bootstrap-navbar.html" %}
        {% endwith %}
    {% endblock %}

    <h1 class="tituloPaginas textoBlanco">{% block HeaderPagina %}{% endblock %}</h1>

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_javascript jquery=1 %}
    {% bootstrap_messages %}

    <script type="text/javascript">
   function toggle_visibility(id) {
       var e = document.getElementById(id);
       if(e.style.display == 'block')
          e.style.display = 'none';
       else
          e.style.display = 'block';
   }
    </script>

    {% block content %}{% endblock %}

</body>

reportesVC/templates/reportesVC/detalleCalculo.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página del reporte de calculo de {{object.tipoReporte.nombreLargo}}
{% endblock %}

{% block content %}
	<div class="textoBlanco">
	<p>Se ejecuto el reporte con la siguiente informacion:</p>
	<ul>
		<li>ID: {{ object.id }}</li>
		<li>Tipo Reporte: {{ object.tipoReporte.nombre }}</li>
		<li>Semana: {{ object.semana }}</li>
		<li>Año Periodo: {{ object.anoPeriodo }}</li>
		<li>Mes Periodo: {{ object.mesPeriodo.nombre }}</li>
		<li>Dia Inicia Periodo: {{ object.diaIniciaPeriodo}}</li>
		<li>Dia Fin Periodo: {{ object.diaFinPeriodo}}</li>
		<li>Fecha Ejecución: {{ object.fechaEjecucion}}</li>
		<li>Estatus: {{ object.estatus}}</li>
		<li>Nombre Archivo: {{ object.nombreArchivo}}</li>
		<li>Ruta Archivo: {{ object.rutaArchivo}}</li>
		<li>Nombre Zip: {{ object.nombreZip}}</li>
	</ul>

	<form action="{{ request.build_absolute_uri }}descargarFile/" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<button class="submitForm" type="submit">{% bootstrap_icon "star" %}Descarga Archivo</button>
	</form>
	</div>
{% endblock %}

reportesVC/templates/reportesVC/detalleReporte.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página del reporte  de {{object.tipoReporte.nombreLargo}}
{% endblock %}

{% block content %}
<div class="textoBlanco">
	<p>Se ejecuto el reporte con la siguiente informacion:</p>
	<ul>
		<li>ID: {{ object.id }}</li>
		<li>Tipo Reporte: {{ object.tipoReporte.nombre }}</li>
		<li>Semana: {{ object.semana }}</li>
		<li>Año Periodo: {{ object.anoPeriodo }}</li>
		<li>Mes Periodo: {{ object.mesPeriodo.nombre }}</li>
		<li>Dia Inicia Periodo: {{ object.diaIniciaPeriodo}}</li>
		<li>Dia Fin Periodo: {{ object.diaFinPeriodo}}</li>
		<li>Fecha Ejecución: {{ object.fechaEjecucion}}</li>
		<li>Estatus: {{ object.estatus}}</li>
		<li>Nombre Archivo: {{ object.nombreArchivo}}</li>
		<li>Ruta Archivo: {{ object.rutaArchivo}}</li>
		<li>Nombre Zip: {{ object.nombreZip}}</li>
	</ul>

 	<div class="row">
		<div class="col-sm-1 text-left">
		</div>
		<div class="col-sm-2 text-center">
			<form action="{{ request.build_absolute_uri }}descargarZip/" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<button class="submitForm" type="submit">{% bootstrap_icon "star" %}Descarga Zip</button>
			</form>
		</div>
		<div class="col-sm-3 text-center">
			 {% if tipo_nombre == VentasPdf%}
				<form action="{{ request.build_absolute_uri }}descargarRepCXC/" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<button class="submitForm" type="submit">{% bootstrap_icon "star" %}Descarga Reporte CXC</button>
				</form>
			{% endif %}
		</div>
		<div class="col-sm-6 text-left">
		</div>
	</div>
</div>
{% endblock %}

reportesVC/templates/reportesVC/ejecutarCalculo.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página de ejecucion de calculos de {{tipo_nombre_largo}}
{% endblock %}

{% block content %}
    <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
            <p>Subir o sustituir los archivos de configuración:</p>
                <form action="{{ request.build_absolute_uri }}subirArchivo/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-12 text-left">
                        <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoArchivo" value="archivoExcepciones" title="Text to show">Archivo Configuraciones Clientes y Aerolineas.
                                <span class="masDetalle" onclick="toggle_visibility('detallesConfCliAL');">+/-</span>
                                <div class="detalles" id="detallesConfCliAL">Las columnas deben llevar este orden: [CLIENTE | LINEA AEREA | COMISION | NOTA]</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoMex">Archivo con Codigos IATA de Mexico.
                                <span class="masDetalle" onclick="toggle_visibility('detallesMex');">+/-</span>
                                <div class="detalles" id="detallesMex">Las columnas deben llevar este orden: [CODIGO IATA | AEROPUERTO | ESTADO]</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoEua">Archivo con Codigos IATA de Estados Unidos.
                                <span class="masDetalle" onclick="toggle_visibility('detallesEua');">+/-</span>
                                <div class="detalles" id="detallesEua">Las columnas deben llevar este orden: [CODIGO IATA | AEROPUERTO | ESTADO]</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoCan">Archivo con Codigos IATA de Canada.
                                <span class="masDetalle" onclick="toggle_visibility('detallesCan');">+/-</span>
                                <div class="detalles" id="detallesCan">Las columnas deben llevar este orden: [CODIGO IATA | AEROPUERTO | ESTADO]</div>
                            </li>

                            <li><input type="radio" name="CBtipoArchivo" value="archivoCsv" checked="checked">Archivo de trabajo de la semana.
                                <span class="masDetalle" onclick="toggle_visibility('detallesArchivo');">+/-</span>
                                <div class="detalles" id="detallesArchivo">Detalles Archivo CSV</div>
                            </li>

                        </ul>
                         </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="subeArchivo">{% bootstrap_icon "star" %}Sube Archivo</button>
                            <button class="submitForm" type="submit" name="bajaArchivo">{% bootstrap_icon "star" %}Baja Archivo</button>
                        </div>
                    </div>
                </form>


                {% if status != "Nuevo" and status != "SubidoConf" and status != "Error" %}
                    <br>
                    <form action="{% url 'reportesVC:ejecutaComisiones' tipoNombre=tipo_nombre status='ejecutando'%}" method="post">
                        {% csrf_token %}
                        {% for variable in variables_ultimo_reporte %}
                            {% if variable.id != 3%}
                                <div class="row">
                                    <div class="col-sm-12 text-left">
                                        <label class="labelForm" for="{{ variable.valor }}">{{ variable.nombre }}:</label>
                                    <!--/div>
                                    <div class="col-sm-9 text-left"-->
                                        {% if variable.editable == 1%}
                                            <input class="textForm" type="text" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}" value="{{ variable.valor }}" />
                                        {% else %}
                                            <label class="labelTextForm" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}">{{ variable.valor }}</label>
                                        {% endif %}
                                    </div>
                                </div>
                                    <!--input type="text" name="{{variable.nombre}}" id="variable{{ forloop.counter }}" value="{{ variable.id }}" /-->
                            {% else %}
                                <!--label for="{{ tipo_valor }}">{{ variable.nombre }}</label-->

                                <input type="hidden" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}" value="{{ tipo_valor }}" />
                                <!--input type="text" name="{{variable.nombre}}" id="variable{{ forloop.counter }}" value="{{ variable.id }}" /-->
                                <!--br /-->
                            {% endif %}
                        {% endfor %}

                        <div class="row">
                            <div class="col-sm-6 text-right"></div>
                            <div class="col-sm-6 text-left">
                                <button class="submitForm" type="submit">{% bootstrap_icon "star" %} Ejecuta Reporte</button>
                            </div>
                        </div>
                    </form>
                {% endif %}
      </div>
    </div>
{% endblock %}

reportesVC/templates/reportesVC/ejecutarReporte.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página de ejecucion de reporte de {{tipo_nombre_largo}}
{% endblock %}

{% block content %}
    <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
                <form action="{{ request.build_absolute_uri }}subirArchivo/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            {% if perms.reportesVC.can_run_Report %}
                                <button class="submitForm" type="submit">{% bootstrap_icon "star" %}Sube Archivo</button>
                            {% endif %}
                        </div>
                    </div>
                </form>

                {% if status != "Nuevo" and status != "Error"%}
                    <br>
                    <form action="{% url 'reportesVC:creaReporte' tipoNombre=tipo_nombre status='ejecutando'%}" method="post">
                        {% csrf_token %}
                        {% for variable in variables_ultimo_reporte %}
                            {% if variable.id != 3%}
                                <div class="row">
                                    <div class="col-sm-12 text-left">
                                        <label class="labelForm" for="{{ variable.valor }}">{{ variable.nombre }}:</label>
                                    <!--/div>
                                    <div class="col-sm-9 text-left"-->
                                        {% if variable.editable == 1%}
                                            <input class="textForm" type="text" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}" value="{{ variable.valor }}" />
                                        {% else %}
                                            <label class="labelTextForm" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}">{{ variable.valor }}</label>
                                        {% endif %}
                                    </div>
                                </div>
                                    <!--input type="text" name="{{variable.nombre}}" id="variable{{ forloop.counter }}" value="{{ variable.id }}" /-->
                            {% else %}
                                <!--label for="{{ tipo_valor }}">{{ variable.nombre }}</label-->
                                <input type="hidden" name="{{ variable.id }}_{{variable.nombre}}" id="{{ variable.id }}" value="{{ tipo_valor }}" />
                                <!--input type="text" name="{{variable.nombre}}" id="variable{{ forloop.counter }}" value="{{ variable.id }}" /-->
                                <!--br /-->
                            {% endif %}
                        {% endfor %}

                        <div class="row">
                            <div class="col-sm-6 text-left">
                                <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoReporte" value="reporteViejo" checked="checked"> Formato Anterior
                                <span class="masDetalle" onclick="toggle_visibility('detallesViejo');">+/-</span>
                                <div class="detalles" id="detallesViejo">
                                    {% if tipo_valor == 1%}
                                        <p>Las columnas deben llevar el siguiente orden:</p>
                                        <p>[CLIENTE | NOMBRE | SERIE | FACTURA | FECHA | PASAJERO | BOLETO | RUTA | FORMA DE PAGO | TARIFA* | IVA* | TUA* | TOTAL*]</p>
                                        <p>Los * indican formato de numero.</p>
                                    {% endif %}
                                    {% if tipo_valor == 2%}
                                        <p>Las columnas deben llevar el siguiente orden:</p>
                                        <p>[CLIENTE | NOMBRE | SERIE | FACTURA | FECHA | PASAJERO | LINEA AEREA | BOLETO | RUTA |  TARIFA* | %* | COM* | IVA* | TOTAL* | CLASES | AEROLINEAS]</p>
                                        <p>Los * indican formato de numero.</p>
                                    {% endif %}
                                </div>
                            </li>
                            <li><input type="radio" name="CBtipoReporte" value="reporteNuevo"> Nuevo Formato
                                <span class="masDetalle" onclick="toggle_visibility('detallesNuevo');">+/-</span>
                                <div class="detalles" id="detallesNuevo">
                                    {% if tipo_valor == 1%}
                                        Solo existe formato Anterior, ver instrucciones de formato anterior
                                    {% endif %}
                                    {% if tipo_valor == 2%}
                                        <p>Las columnas deben llevar el siguiente orden:</p>
                                        <p>[CLIENTE | NOMBRE | BOLETO | SERIE | FACTURA | FECHA | PASAJERO | LINEA AEREA | AEROLINEAS | INTERLINEAL | PAIS ORIGEN |  CIUDAD ORIGEN | PAIS DESTINO | CIUDAD DESTINO | RUTA | CODIGO COMPARTIDO | CLASES | TARIFA BASE* | % COMISION BSP | COMISION BSP* | % COMISION | COMISION* | IVA* | TOTAL*]</p>
                                        <p>Los * indican formato de numero.</p>
                                    {% endif %}
                                </div>
                            </li>
                        </ul>
                            </div>
                            <div class="col-sm-6 text-left">
                                {% if perms.reportesVC.can_run_Report%}
                                    <button class="submitForm" type="submit">{% bootstrap_icon "star" %} Ejecuta Reporte</button>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                {% endif %}
      </div>
    </div>
{% endblock %}

reportesVC/templates/reportesVC/index.html
{% extends '../base.html' %}

{% block HeaderPagina %}
    Bienvenido a la pagina de reportes de VK
{% endblock %}

{% block content %}
    <div class="center textoBlanco">
    </div>
{% endblock %}