reportesVC/urls.py
from django.conf.urls import url

from . import views

app_name = 'reportesVC'
urlpatterns = [
    ##(?P<question_id>[0-9]+)
    ###View normal
    #url(r'^(?P<tipoNombre>[\w]+)/(?P<reporteId>[0-9]+)/$', views.reporte, name='reporte'),
    ###Quick view provided bydjango
    url(r'^$', views.index, name='index'),

    ##url(r'^rp(?P<tipoNombre>[\w]+)/$', views.reportes, name='reportes'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/$', views.reportes, name='reportes'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/new/$', views.creaReporte, name='creaReporte'),
    url(r'^rp(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivo/$', views.subirArchivo, name='subirArchivo'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/$', views.ReporteView.as_view(), name='reporte'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarZip/$', views.descargarZip, name='descargarZip'),
    url(r'^rp(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarRepCXC/$', views.descargarRepCXC, name='descargarRepCXC'),

    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/$', views.calculos, name='calculos'),
    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/new/$', views.ejecutaComisiones, name='ejecutaComisiones'),
    url(r'^cal(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivo/$', views.subirArchivoCal, name='subirArchivoCal'),
    url(r'^cal(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/$', views.CalculoView.as_view(), name='calculo'),
    url(r'^cal(?P<tipoNombre>[\w]+)/(?P<pk>[0-9]+)/descargarFile/$', views.descargarFile, name='descargarFile'),

    url(r'^admin/Conta/$', views.adminConta, name='adminConta'),

    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionBancos$', views.conciliacionBancos, name='conciliacionBancos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaBancos/$', views.conciliaBancos, name='conciliaBancos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/subirArchivoCon/$', views.subirArchivoCon, name='subirArchivoCon'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionSAT$', views.conciliacionSAT, name='conciliacionSAT'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaSAT/$', views.conciliaSAT, name='conciliaSAT'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionIngresos$', views.conciliacionIngresos, name='conciliacionIngresos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaIngresos/$', views.conciliaIngresos, name='conciliaIngresos'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliacionMontoClave$', views.conciliacionMontoClave, name='conciliacionMontoClave'),
    url(r'^con(?P<tipoNombre>[\w]+)/st(?P<status>[\w]+)/conciliaMontoClave/$', views.conciliaMontoClave, name='conciliaMontoClave'),
]

reportesVC/templates/conta/adminConta.html
{% extends '../base.html' %}

{% block HeaderPagina %}
    Página admin de conta
{% endblock %}

{% block content %}


	<script type="text/javascript" src="//code.jquery.com/jquery-1.12.4.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>



    <script type="text/javascript">
    <!--http://legacy.datatables.net/usage/i18n-->
    $(document).ready(function(){
        $('#myTable').dataTable(
        {
            "order": [[ 3, "desc" ]],
            "bFilter": true,
            "oLanguage": {
            "sInfo": "Registros totales: _TOTAL_ / Mostrados del _START_ al _END_",
            "sZeroRecords": "No se encontr&oacute; el registro",
            "sLengthMenu": "_MENU_ Registros por pagina",
            "sInfoFiltered": "( Filtrado de _MAX_ registros )",
            "sSearch":"Buscar",
            "oPaginate": {
                "sPrevious": "<",
                "sNext": ">",
                "sFirst": "Primera",
                "sLast": "Ultima",
            }
        }
        }
        );
    });
    </script>

    <div class="center">
        {% csrf_token %}

        <div class="col-sm-1"></div>
        <div class="col-sm-10">
        <table id="myTable" class="tablaActu table table-condensed table-responsive table-striped pagination">
            <thead>
                <tr>
                    <th class="col-sm-2 centerText">TipoReporte</th>
                    <th class="col-sm-4 centerText">NombreArchivo</th>
                    <th class="col-sm-1 centerText">Estatus</th>
                    <th class="col-sm-3 centerText">Fecha Ejecucion</th>
                    <th class="col-sm-2 centerText">Usuario</th>
                </tr>
            </thead>
            <tbody>
                {%for log in lista_log_conta %}
                    <tr>
                        <td>{{ log.tipoReporte.nombreLargo }}</td>
                        <td>{{ log.nombreArchivo }}</td>
                        <td>{{ log.estatus }}</td>
                        <td>{{ log.fechaEjecucion }}</td>
                        <td>{{ log.user.username }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <div class="col-sm-1"></div>
    </div>

{% endblock %}

reportesVC/templates/conta/conciliacionBancos.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página de ejecucion de conciliacion [{{tipo_nombre_largo}}]
{% endblock %}

{% block content %}
     <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
               <br>
                <form action="{% url 'reportesVC:conciliaBancos' tipoNombre=tipo_nombre status='ejecutando'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 text-right"></div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="conciliar">{% bootstrap_icon "star" %} Conciliar</button>
                        </div>
                    </div>


                <form action="{{ request.build_absolute_uri }}subirArchivo/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}

                     <div class="row">
                        <div class="col-sm-3 text-left">
                            <p>Selecciona Agencia:</p>
                            <ul class="listaArchivos">
                                <!--li><input type="radio" name="CBAgencia" value="Contravel" checked="checked" title="Text to show">Contravel
                                </li-->
                                <li><input type="radio" name="CBAgencia" value="VK" checked="checked">Viajes Kokai
                                </li>
                                <li><input type="radio" name="CBAgencia" value="Otra">Otra
                                </li>
                            </ul>
                        </div>
                         <div class="col-sm-9 text-left">
                             <p>Selecciona fecha:</p>
                             <input id="currentDate" class="calendario" type="date" name="DATEreportes" />
                        </div>
                    </div>
                    <p>Subir o sustituir los archivos de configuración:</p>
                    <div class="row">
                        <div class="col-sm-12 text-left">
                        <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoArchivo" value="archivoSaldos" title="Text to show">Archivo Saldos.
                                <span class="masDetalle" onclick="toggle_visibility('detallesConfCliAL');">+/-</span>
                                <div class="detalles" id="detallesConfCliAL">Las columnas deben llevar este orden: [CUENTA | SALDO ICAAV | SALDO BANCOS] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoBancos">Archivo Bancos.
                                <span class="masDetalle" onclick="toggle_visibility('detallesMex');">+/-</span>
                                <div class="detalles" id="detallesMex">Las columnas deben llevar este orden: [FECHA | DESCRIPCION | CARGO | ABONO | CUENTA] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoAuxiliar" checked="checked">Archivo de ICAAV.
                                <span class="masDetalle" onclick="toggle_visibility('detallesArchivo');">+/-</span>
                                <div class="detalles" id="detallesArchivo">Archivo auxiliar de ICAAV en formato CSV sin comas y sin titulos. (Agregar en este historicos)</div>
                            </li>

                        </ul>
                         </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="subeArchivo">{% bootstrap_icon "star" %}Sube Archivo</button>
                            <button class="submitForm" type="submit" name="boton" value="bajaArchivo">{% bootstrap_icon "star" %}Baja Archivo</button>
                        </div>
                    </div>
                </form>
                </form>


      </div>
    </div>
{% endblock %}

reportesVC/templates/conta/conciliacionIngresos.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página de ejecucion de conciliacion [{{tipo_nombre_largo}}]
{% endblock %}

{% block content %}
     <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
               <br>
                <form action="{% url 'reportesVC:conciliaIngresos' tipoNombre=tipo_nombre status='ejecutando'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 text-right"></div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="conciliar">{% bootstrap_icon "star" %} Conciliar</button>
                        </div>
                    </div>
                <form action="{{ request.build_absolute_uri }}subirArchivoCon/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                     <div class="row">
                        <div class="col-sm-3 text-left">
                            <p>Selecciona Agencia:</p>
                            <ul class="listaArchivos">
                                <!--li><input type="radio" name="CBAgencia" value="Contravel" checked="checked" title="Text to show">Contravel
                                </li-->
                               <li><input type="radio" name="CBAgencia" value="VK" checked="checked">Viajes Kokai
                                </li>
                                <li><input type="radio" name="CBAgencia" value="Otra">Otra
                                </li>
                            </ul>
                        </div>
                         <div class="col-sm-9 text-left">
                             <p>Selecciona fecha:</p>
                             <input id="currentDate" class="calendario" type="date" name="DATEreportes" />
                        </div>
                    </div>
                    <p>Subir o sustituir los archivos de configuración:</p>
                    <div class="row">
                        <div class="col-sm-12 text-left">
                        <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoArchivo" value="archivoVentas" title="Text to show">Archivo Ventas.
                                <span class="masDetalle" onclick="toggle_visibility('detallesConfCliAL');">+/-</span>
                                <div class="detalles" id="detallesConfCliAL">En el archivo del mes a conciliar se deben o pueden meter todos los meses de ventas que se deseen para que los ingresos localicen todas las ventas. Las columnas deben llevar este orden: [datos_factura_id_cliente|datos_factura_id_serie|datos_factura_fac_numero|detalle_factura_nom_pasajero|detalle_factura_numero_bol|detalle_factura_concepto|forma_pago|detalle_factura_tarifa_mon_base|iva|tua|otros|detalle_factura_descuento|detalle_factura_iva_desc|datos_factura_fecha|sucursales_cve|datos_factura_id_sucursal|proveedores_id_tipo_proveedor|datos_factura_id_stat|datos_factura_cl_nombre|id_unidad_negocio|id_oriven] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoDiarios" checked="checked">Diario de ICAAV.
                                <span class="masDetalle" onclick="toggle_visibility('detallesArchivo');">+/-</span>
                                <div class="detalles" id="detallesArchivo">Archivo diario de ICAAV en formato CSV sin comas y sin titulos.
                                Las columnas deben llevar este orden: [datos_poliza_id_sucursal|datos_poliza_anio|datos_poliza_mes|datos_poliza_tipo|datos_poliza_num_poliza|datos_poliza_fecha|datos_poliza_concepto|datos_poliza_estatus|datos_poliza_id_stat|datos_poliza_fecha_mod|detalle_poliza_id_sucursal|detalle_poliza_anio|detalle_poliza_mes|detalle_poliza_tipo|detalle_poliza_num_poliza|detalle_poliza_movimiento|detalle_poliza_cuen_num_cuenta|detalle_poliza_referencia|detalle_poliza_concepto_mov|detalle_poliza_tipo_cambio|detalle_poliza_cargo|detalle_poliza_abono|detalle_poliza_documento|detalle_poliza_id_serie|detalle_poliza_fac_numero|detalle_poliza_id_proveedor|detalle_poliza_numero_bol|detalle_poliza_origen|detalle_poliza_id_stat|detalle_poliza_fecha_mod|cuentas_contab_nombre_cta|sucursales_cve|detalle_poliza_uuid|folio_cheque] en formato CSV sin comas y sin titulos.</div>
                            </li>

                        </ul>
                         </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="subeArchivo">{% bootstrap_icon "star" %}Sube Archivo</button>
                        </div>
                    </div>
                </form>
                </form>


      </div>
    </div>
{% endblock %}

reportesVC/templates/conta/conciliacionMontoClave.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block HeaderPagina %}
    Página de ejecucion de conciliacion [{{tipo_nombre_largo}}]
{% endblock %}

{% block content %}
     <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
               <br>
                <form action="{% url 'reportesVC:conciliaMontoClave' tipoNombre=tipo_nombre status='ejecutando'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 text-right"></div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="conciliar">{% bootstrap_icon "star" %} Conciliar</button>
                        </div>
                    </div>
                <form action="{{ request.build_absolute_uri }}subirArchivoCon/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                    <p>Subir o sustituir los archivos de configuración:</p>
                    <div class="row">
                        <div class="col-sm-12 text-left">
                        <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoArchivo" value="archivoBase" title="Text to show">Archivo Base.
                                <span class="masDetalle" onclick="toggle_visibility('detallesConfCliAL');">+/-</span>
                                <div class="detalles" id="detallesConfCliAL">En el archivo base a conciliar se deben o pueden meter todos los meses que se deseen. Las columnas deben llevar este orden: [monto|clave|dato1|dato2|dato3|dato4|dato5|dato6|dato7|dato8|dato9|dato10|dato11|dato12|dato13|dato14|dato15] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoAConciliar" checked="checked">Archivo a Conciliar.
                                <span class="masDetalle" onclick="toggle_visibility('detallesArchivo');">+/-</span>
                                <div class="detalles" id="detallesArchivo">En el archivo para conciliar se deben o pueden meter todos los meses que se deseen. Las columnas deben llevar este orden: [monto|clave|dato1|dato2|dato3|dato4|dato5|dato6|dato7|dato8|dato9|dato10|dato11|dato12|dato13|dato14|dato15] en formato CSV sin comas y sin titulos.</div>
                            </li>

                        </ul>
                         </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="subeArchivo">{% bootstrap_icon "star" %}Sube Archivo</button>
                        </div>
                    </div>
                </form>
                </form>


      </div>
    </div>
{% endblock %}

reportesVC/templates/conta/conciliacionSAT.html
{% extends '../base.html' %}
{% load bootstrap3 %}

{% block tituloPagina %}
    Página de ejecucion de conciliacion [{{tipo_nombre_largo}}]
{% endblock %}

{% block HeaderPagina %}
    Página de ejecucion de conciliacion [{{tipo_nombre_largo}}]
{% endblock %}

{% block content %}
     <div class="row textoBlanco">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
               <br>
                <form action="{% url 'reportesVC:conciliaSAT' tipoNombre=tipo_nombre status='ejecutando'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 text-left">
                            <p>Selecciona Meses:</p>
                            <ul class="listaMeses">
                                <li><input type="checkbox" name="CBMes" value="01">Enero
                                </li>
                                <li><input type="checkbox" name="CBMes" value="02">Febrero
                                </li>
                                <li><input type="checkbox" name="CBMes" value="03">Marzo
                                </li>
                                <li><input type="checkbox" name="CBMes" value="04">Abril
                                </li>
                                <li><input type="checkbox" name="CBMes" value="05">Mayo
                                </li>
                                <li><input type="checkbox" name="CBMes" value="06">Junio
                                </li>
                                <li><input type="checkbox" name="CBMes" value="07">Julio
                                </li>
                                <li><input type="checkbox" name="CBMes" value="08">Agosto
                                </li>
                                <li><input type="checkbox" name="CBMes" value="09">Septiembre
                                </li>
                                 <li><input type="checkbox" name="CBMes" value="10">Octubre
                                </li>
                                <li><input type="checkbox" name="CBMes" value="11">Noviembre
                                </li>
                                <li><input type="checkbox" name="CBMes" value="12">Diciembre
                                </li>
                            </ul>
                        </div>
                    </div>
                     <div class="row">
                        <div class="col-sm-6 text-left">
                            Año 2 digitos: <input class="textFormSmall" type="text" name="InpAno"  maxlength="2"/>
                        </div>
                     </div>


                    <div class="row">
                        <div class="col-sm-6 text-right"></div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="conciliar">{% bootstrap_icon "star" %} Conciliar</button>
                        </div>
                    </div>

                <hr>
                <form action="{{ request.build_absolute_uri }}subirArchivoCon/" method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}

                     <div class="row">
                        <div class="col-sm-3 text-left">
                            <p>Selecciona Agencia:</p>
                            <ul class="listaArchivos">
                                <!--li><input type="radio" name="CBAgencia" value="Contravel" checked="checked" title="Text to show">Contravel
                                </li-->
                                <li><input type="radio" name="CBAgencia" value="VK" checked="checked">Viajes Kokai
                                </li>
                                <li><input type="radio" name="CBAgencia" value="Otra">Otra
                                </li>
                            </ul>
                        </div>
                         <div class="col-sm-9 text-left">
                             <p>Selecciona fecha:</p>
                             <input id="currentDate" class="calendario" type="date" name="DATEreportes" />
                        </div>
                    </div>
                    <p>Subir o sustituir los archivos de configuración:</p>
                    <div class="row">
                        <div class="col-sm-12 text-left">
                        <ul class="listaArchivos">
                            <li><input type="radio" name="CBtipoArchivo" value="archivoSAT" title="Text to show">Archivo SAT (Recibidas y Emitidas).
                                <span class="masDetalle" onclick="toggle_visibility('detallesConfCliAL');">+/-</span>
                                <div class="detalles" id="detallesConfCliAL">Las columnas deben llevar este orden: [Verificado ó Asoc.|Estado SAT|Version|Tipo|Fecha Emision|Fecha Timbrado|EstadoPago|FechaPago|Serie|Folio|UUID|UUID Relacion|RFC Emisor|Nombre Emisor|LugarDeExpedicion|RFC Receptor|Nombre Receptor|ResidenciaFiscal|NumRegIdTrib|UsoCFDI|SubTotal|Descuento|Total IEPS|IVA 16%|Retenido IVA|Retenido ISR|ISH|Total|TotalOriginal|Total Trasladados|Total Retenidos|Total LocalTrasladado|Total LocalRetenido|Complemento|Moneda|Tipo De Cambio|FormaDePago|Metodo de Pago|NumCtaPago|Condicion de Pago|Conceptos|Combustible|IEPS 3%|IEPS 6%|IEPS 7%|IEPS 8%|IEPS 9%|IEPS 26.5%|IEPS 30%|IEPS 53%|IEPS 160%|Archivo XML|Direccion Emisor|Localidad Emisor] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoNomina">Archivo Nomina.
                                <span class="masDetalle" onclick="toggle_visibility('detallesMex');">+/-</span>
                                <div class="detalles" id="detallesMex">Las columnas deben llevar este orden: [Verificado ó Asoc.|EstadoSAT|FechaEmision|Serie|Folio|UUID|RFC Receptor|NombreReceptor|RegistroPatronal |TipoNomina |FechaPago |FechaInicialPago |FechaFinalPago |NumDiasPagados |TotalPercepciones |TotalDeducciones |TotalOtrosPagos |SubTotal|Descuento|ISR XML|Total|MetodoPago|Regimen|ArchivoXML|Conceptos|Version |Moneda|TipoCambio|ReceptorCurp |NumSeguridadSocial |FechaInicioRelLaboral |Antigüedad |TipoContratoTipoContrato|Sindicalizado |TipoJornada |TipoRegimen |NumEmpleado |Departamento |Pueston |RiesgoPuesto |PeriodicidadPago |Banco |CuentaBancaria |SalarioBaseCotApor |SalarioDiarioIntegrado |ClaveEntFed |TotalSueldosPer|TotalSeparacionIndemnizacionPer|TotalJubilacionPensionRetiroPer|TotalGravadoPersepcion |TotalExentoPersepcion|TotalOtrasDeducciones |TotalImpuestosRetenidosDed] en formato CSV sin comas y sin titulos.</div>
                            </li>
                            <li><input type="radio" name="CBtipoArchivo" value="archivoDiarios" checked="checked">Diario de ICAAV.
                                <span class="masDetalle" onclick="toggle_visibility('detallesArchivo');">+/-</span>
                                <div class="detalles" id="detallesArchivo">Archivo diario de ICAAV en formato CSV sin comas y sin titulos.
                                Las columnas deben llevar este orden: [datos_poliza_id_sucursal|datos_poliza_anio|datos_poliza_mes|datos_poliza_tipo|datos_poliza_num_poliza|datos_poliza_fecha|datos_poliza_concepto|datos_poliza_estatus|datos_poliza_id_stat|datos_poliza_fecha_mod|detalle_poliza_id_sucursal|detalle_poliza_anio|detalle_poliza_mes|detalle_poliza_tipo|detalle_poliza_num_poliza|detalle_poliza_movimiento|detalle_poliza_cuen_num_cuenta|detalle_poliza_referencia|detalle_poliza_concepto_mov|detalle_poliza_tipo_cambio|detalle_poliza_cargo|detalle_poliza_abono|detalle_poliza_documento|detalle_poliza_id_serie|detalle_poliza_fac_numero|detalle_poliza_id_proveedor|detalle_poliza_numero_bol|detalle_poliza_origen|detalle_poliza_id_stat|detalle_poliza_fecha_mod|cuentas_contab_nombre_cta|sucursales_cve|detalle_poliza_uuid|folio_cheque] en formato CSV sin comas y sin titulos.</div>
                            </li>

                        </ul>
                         </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 text-right">
                            <input type="file" name="myfile">
                        </div>
                        <div class="col-sm-6 text-left">
                            <button class="submitForm" type="submit" name="boton" value="subeArchivo">{% bootstrap_icon "star" %}Sube Archivo</button>
                        </div>
                    </div>
                </form>
                </form>


      </div>
    </div>
{% endblock %}